kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  egress:
  - {}
  # deny ingress traffic
  ingress: []
  policyTypes:
  - Ingress
  - Egress

